#' @title spp_strategy_poleward
#' @description Creates a summary table of significant and spatial/thermal trends,
#' incorporating poleward shift logic for latitude if hemisphere data is provided.
#' Assumes longitude trends may be based on coordinates with Antimeridian as 0.
#'
#' @param spp_trends A data frame containing trend indicators per species,
#'   generated by spp_trend_world. It is expected to contain columns such as:
#'   - "species": Species names.
#'   - "trend": Trend values.
#'   - "t": t-statistic values.
#'   - "pvalue": p-values.
#'   - "responses": Response variable (e.g., Lat, Lon, Tmx).
#'   - "dif_t": Difference in t-statistic values (e.g., from segmented regression).
#'   - "dif_pvalue": Difference in p-values (e.g., from segmented regression).
#'   - "n": Sample size.
#'   - "hemisphere": Hemisphere information ("North", "South").
#' @param spp_trends_world_results The result from spp_trend_world.
#' @param bonferroni The Bonferroni adjusted significance threshold value.
#' @param responses A vector of response variable names (e.g., "Lat", "Lon", "Tmx").
#'
#' @return A data frame summarizing significant trends and spatial/thermal
#'   classification of species. Latitude classification will be 'Spatial_Lat_Poleward'
#'   if hemisphere info is provided and used. Longitude classification interpretation
#'   depends on whether input trends used transformed coordinates (Antimeridian=0).
#'   If Tmx is included in responses, it will also include the trend values from spp_trends_world_results.
#'
#' @importFrom dplyr select mutate case_when all_of lead
#' @importFrom tidyr pivot_wider
#'
#' @examples
#' \dontrun{
#' spp_trends_results <- data.frame(
#'   species = paste0("spp_", 1:10),
#'   responses = rep(c("Lat", "Lon"), each = 5),
#'   trend = runif(10, -0.5, 0.5),
#'   t = runif(10, -2, 2),
#'   pvalue = runif(10, 0, 0.1),
#'   ci_95_max = runif(10, 0.05, 0.2),
#'   ci_95_min = runif(10, -0.1, 0.05),
#'   dif_t = runif(10, -1, 1.5),
#'   dif_pvalue = runif(10, 0.001, 0.9),
#'   n = runif(10, 40, 60),
#'   hemisphere = sample(c("North", "South"), 10, replace = TRUE)
#' )
#' spp <- unique(spp_trends_results$species)
#' bonferroni_alpha = 0.05 / length(spp) # Correct Bonferroni calculation
#' responses = c("Lat","Lon")
#' spp_strategy_poleward_results <- spp_strategy_poleward(
#'   spp_trends_results,
#'   spp_trends_world_results = spp_trends_results,
#'   bonferroni = bonferroni_alpha,
#'   responses = responses
#' )
#' print(spp_strategy_poleward_results)
#' }
#'
#' @export
spp_strategy_poleward <- function(spp_trend_world_result, bonferroni = 0.05, responses = responses) {
  classify_spatial_standard <- function(p, dif_p, trend) {
    dplyr::case_when(
      p > bonferroni ~ "SC",
      p <= bonferroni & dif_p <= bonferroni & trend > 0 ~ "SA",
      p <= bonferroni & dif_p <= bonferroni & trend < 0 ~ "SD",
      TRUE ~ "SC"
    )
  }

  classify_lat_poleward <- function(pvalue, dif_pvalue, trend, hemisphere) {
    dplyr::case_when(
      pvalue > bonferroni ~ "SC",
      pvalue <= bonferroni & dif_pvalue <= bonferroni & trend > 0 & hemisphere == "North" ~ "SP",
      pvalue <= bonferroni & dif_pvalue <= bonferroni & trend < 0 & hemisphere == "North" ~ "SE",
      pvalue <= bonferroni & dif_pvalue <= bonferroni & trend < 0 & hemisphere == "South" ~ "SE",
      pvalue <= bonferroni & dif_pvalue <= bonferroni & trend > 0 & hemisphere == "South" ~ "SP",
      TRUE ~ "SC"
    )
  }

  classify_thermal <- function(p, dif_p, trend) {
    dplyr::case_when(
      p > bonferroni ~ "TC",
      p <= bonferroni & dif_p <= bonferroni & trend < 0 ~ "TA",
      p <= bonferroni & dif_p <= bonferroni & trend > 0 ~ "TT",
      TRUE ~ "TC"
    )
  }

  required_cols <- c("species", "trend", "t", "pvalue", "responses", "dif_t", "dif_pvalue", "n", "hemisphere")

  if (!all(required_cols %in% names(spp_trends_world_results))) {
    missing_cols <- setdiff(required_cols, names(spp_trends_world_results))
    stop(paste("Error: The following columns were not found in 'spp_trends_world_results':", paste(missing_cols, collapse = ", "), ". The required columns are:", paste(required_cols, collapse = ", ")))
  }

  strategies <- spp_trends_world_results %>%
    dplyr::select(dplyr::all_of(intersect(required_cols, names(spp_trends_world_results)))) %>%
    dplyr::mutate(
      Spatial_Lat_Poleward = dplyr::case_when(
        .data$responses == "Lat" ~ classify_lat_poleward(.data$pvalue, .data$dif_pvalue, .data$trend, .data$hemisphere),
        TRUE ~ NA_character_
      ),
      Spatial_Lon = dplyr::case_when(
        .data$responses == "Lon" ~ classify_spatial_standard(.data$pvalue, .data$dif_pvalue, .data$trend),
        TRUE ~ NA_character_
      ),
      Spatial_Ele = dplyr::case_when(
        .data$responses == "Ele" ~ classify_spatial_standard(.data$pvalue, .data$dif_pvalue, .data$trend),
        TRUE ~ NA_character_
      ),
      Thermal_Tmx = dplyr::case_when(
        .data$responses == "Tmx" ~ classify_thermal(.data$pvalue, .data$dif_pvalue, .data$trend),
        TRUE ~ NA_character_
      ),
      Thermal_Tmn = dplyr::case_when(
        .data$responses == "Tmn" ~ classify_thermal(.data$pvalue, .data$dif_pvalue, .data$trend),
        TRUE ~ NA_character_
      ),
      Thermal_Tme = dplyr::case_when(
        .data$responses == "Tme" ~ classify_thermal(.data$pvalue, .data$dif_pvalue, .data$trend),
        TRUE ~ NA_character_
      )
    ) %>%
    dplyr::group_by(species, hemisphere) %>%
    dplyr::summarise(
      n = sum(n),
      Spatial_Lat_Poleward = dplyr::first(Spatial_Lat_Poleward),
      Spatial_Lon = dplyr::first(Spatial_Lon[!is.na(Spatial_Lon)]),
      Spatial_Ele = dplyr::if_else("Ele" %in% responses, dplyr::first(Spatial_Ele[!is.na(Spatial_Ele)]), NA_character_),
      Thermal_Tmx = dplyr::if_else("Tmx" %in% responses, dplyr::first(Thermal_Tmx[!is.na(Thermal_Tmx)]), NA_character_),
      Thermal_Tmn = dplyr::if_else("Tmn" %in% responses, dplyr::first(Thermal_Tmn[!is.na(Thermal_Tmn)]), NA_character_),
      Thermal_Tme = dplyr::if_else("Tme" %in% responses, dplyr::first(Thermal_Tme[!is.na(Thermal_Tme)]), NA_character_),
      .groups = "drop"
    ) %>%
    tidyr::pivot_wider(names_from = hemisphere, values_from = Spatial_Lat_Poleward, names_prefix = "Lat_") %>%
    dplyr::ungroup()
  return(strategies)
}

