#' @title spp_strategy
#' @description Creates a summary table of significant and spatial/thermal trends,
#' incorporating poleward shift logic for latitude if hemisphere data is provided.
#' Assumes longitude trends may be based on coordinates with Antimeridian as 0.
#'
#' @param spp_trend_result A data frame containing trend indicators per species,
#'    generated by spp_trend. It is expected to contain columns such as:
#'    - "species": Species names.
#'    - "trend": Trend values.
#'    - "t": t-statistic values.
#'    - "pvalue": p-values.
#'    - "responses": Response variable (e.g., Lat, Lon, Tmx).
#'    - "dif_t": Difference in t-statistic values (e.g., from segmented regression).
#'    - "dif_pvalue": Difference in p-values (e.g., from segmented regression).
#'    - "n": Sample size.
#'    - "hemisphere": Hemisphere information ("North", "South", "Both").
#' @param sig_level The significance level (alpha) to use for classification.
#' @param responses A vector of response variable names (e.g., "Lat", "Lon", "Tmx").
#'
#' @return A data frame summarizing significant trends and spatial/thermal
#'    classification of species. Latitude classification will be 'Spatial_Lat_Poleward'
#'    if hemisphere info is provided and used. Longitude classification interpretation
#'    depends on whether input trends used transformed coordinates (Antimeridian=0).
#'    If thermal responses are included in 'responses' (Tmx, Tmn, Tme), they will
#'    also be included in the output. Only responses present in the 'responses'
#'    column of 'spp_trend_result' will have corresponding classification columns
#'    in the output.
#'
#' @importFrom dplyr select mutate case_when all_of lead group_by summarise if_else ungroup
#' @importFrom tidyr pivot_wider
#'
#' @examples
#' \dontrun{
#' # Example data remains the same
#' }
#'
#' @export
spp_strategy <- function(spp_trend_result,
                                  sig_level = 0.05,
                                  responses = responses) {
  classify_spatial_standard <- function(pvalue, dif_pvalue, trend) {
    dplyr::case_when(
      pvalue > sig_level ~ "SC",
      pvalue <= sig_level &
        dif_pvalue <= sig_level & trend > 0 ~ "SA",
      pvalue <= sig_level &
        dif_pvalue <= sig_level & trend < 0 ~ "SD",
      TRUE ~ "SC"
    )
  }
  classify_lat_poleward <- function(pvalue, dif_pvalue, trend, hemisphere) {
    dplyr::case_when(
      pvalue > sig_level ~ "SC",
      pvalue <= sig_level &
        dif_pvalue <= sig_level &
        trend > 0 & hemisphere == "North" ~ "SP",
      pvalue <= sig_level &
        dif_pvalue <= sig_level &
        trend < 0 & hemisphere == "North" ~ "SE",
      pvalue <= sig_level &
        dif_pvalue <= sig_level &
        trend > 0 & hemisphere == "South" ~ "SE",
      pvalue <= sig_level &
        dif_pvalue <= sig_level &
        trend < 0 & hemisphere == "South" ~ "SP",
      pvalue <= sig_level &
        dif_pvalue <= sig_level &
        trend > 0 & hemisphere == "Both" ~ "SA",
      pvalue <= sig_level &
        dif_pvalue <= sig_level &
        trend < 0 & hemisphere == "Both" ~ "SD",
      TRUE ~ "SC"
    )
  }
  classify_thermal <- function(pvalue, dif_pvalue, trend) {
    dplyr::case_when(
      pvalue > sig_level ~ "TC",
      pvalue <= sig_level &
        dif_pvalue <= sig_level & trend < 0 ~ "TA",
      pvalue <= sig_level &
        dif_pvalue <= sig_level & trend > 0 ~ "TT",
      TRUE ~ "TC"
    )
  }

  required_cols <- c(
    "species",
    "trend",
    "t",
    "pvalue",
    "responses",
    "dif_t",
    "dif_pvalue",
    "n",
    "hemisphere"
  )

  if (!all(required_cols %in% names(spp_trend_result))) {
    missing_cols <- setdiff(required_cols, names(spp_trend_result))
    stop(
      paste(
        "Error: The following columns were not found in 'spp_trend_result':",
        paste(missing_cols, collapse = ", "),
        ". The required columns are:",
        paste(required_cols, collapse = ", ")
      )
    )
  }

  strategies <- spp_trend_result %>%
    dplyr::select(dplyr::all_of(intersect(
      required_cols, names(spp_trend_result)
    ))) %>%
    dplyr::mutate(
      Spatial_Lat_Poleward = dplyr::case_when(
        .data$responses == "Lat" ~ classify_lat_poleward(
          .data$pvalue,
          .data$dif_pvalue,
          .data$trend,
          .data$hemisphere
        ),
        TRUE ~ NA_character_
      ),
      Spatial_Lon = dplyr::case_when(
        .data$responses == "Lon" ~ classify_spatial_standard(.data$pvalue, .data$dif_pvalue, .data$trend),
        TRUE ~ NA_character_
      ),
      Spatial_Ele = dplyr::case_when(
        .data$responses == "Ele" ~ classify_spatial_standard(.data$pvalue, .data$dif_pvalue, .data$trend),
        TRUE ~ NA_character_
      ),
      Thermal_Tmx = dplyr::case_when(
        .data$responses == "Tmx" ~ classify_thermal(.data$pvalue, .data$dif_pvalue, .data$trend),
        TRUE ~ NA_character_
      ),
      Thermal_Tmn = dplyr::case_when(
        .data$responses == "Tmn" ~ classify_thermal(.data$pvalue, .data$dif_pvalue, .data$trend),
        TRUE ~ NA_character_
      ),
      Thermal_Tme = dplyr::case_when(
        .data$responses == "Tme" ~ classify_thermal(.data$pvalue, .data$dif_pvalue, .data$trend),
        TRUE ~ NA_character_
      )
    ) %>%
    dplyr::group_by(species, hemisphere) %>%
    dplyr::summarise(
      n = sum(n),
      Spatial_Lat_Poleward = dplyr::first(Spatial_Lat_Poleward),
      Spatial_Lon = if ("Lon" %in% unique(responses))
        dplyr::first(Spatial_Lon[!is.na(Spatial_Lon)])
      else
        NULL,
      Spatial_Ele = if ("Ele" %in% unique(responses))
        dplyr::first(Spatial_Ele[!is.na(Spatial_Ele)])
      else
        NULL,
      Thermal_Tmx = if ("Tmx" %in% unique(responses))
        dplyr::first(Thermal_Tmx[!is.na(Thermal_Tmx)])
      else
        NULL,
      Thermal_Tmn = if ("Tmn" %in% unique(responses))
        dplyr::first(Thermal_Tmn[!is.na(Thermal_Tmn)])
      else
        NULL,
      Thermal_Tme = if ("Tme" %in% unique(responses))
        dplyr::first(Thermal_Tme[!is.na(Thermal_Tme)])
      else
        NULL,
      .groups = "drop"
    ) %>%
    tidyr::pivot_wider(
      names_from = hemisphere,
      values_from = Spatial_Lat_Poleward,
      names_prefix = "Lat_"
    ) %>%
    dplyr::ungroup()
}
